apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kaniko-pod-cleaner-role
  namespace: azure-agent
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]

