apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: ${nodeclass_name}
spec:
  kubelet:
    maxPods: ${karpenter_node_max_pods}
    systemReserved:
        cpu: 100m
        memory: 100Mi
        ephemeral-storage: 1Gi
    kubeReserved:
        cpu: 200m
        memory: 100Mi
        ephemeral-storage: 3Gi
    evictionHard:
        memory.available: 5%
        nodefs.available: 10%
        nodefs.inodesFree: 10%
    evictionSoft:
        memory.available: 500Mi
        nodefs.available: 15%
        nodefs.inodesFree: 15%
    evictionSoftGracePeriod:
        memory.available: 1m
        nodefs.available: 1m30s
        nodefs.inodesFree: 2m
    evictionMaxPodGracePeriod: 60
    imageGCHighThresholdPercent: 85
    imageGCLowThresholdPercent: 80


  amiFamily: ${karpenter_node_ami_family} # AL2

  # Required, discovers subnets to attach to instances
  # Each term in the array of subnetSelectorTerms is ORed together
  # Within a single term, all conditions are ANDed
  subnetSelectorTerms:
  - tags:
      Name: "${karpenter_shared_subnet_tag_regex}"
  - tags:
      Name: "${karpenter_back_subnet_tag_regex}"

  # Required, discovers security groups to attach to instances
  # Each term in the array of securityGroupSelectorTerms is ORed together
  # Within a single term, all conditions are ANDed
  securityGroupSelectorTerms:
  - tags:
      aws:eks:cluster-name: "${cluster_name}"

  # Optional, IAM role to use for the node identity.
  # The "role" field is immutable after EC2NodeClass creation. This may change in the
  # future, but this restriction is currently in place today to ensure that Karpenter
  # avoids leaking managed instance profiles in your account.
  # Must specify one of "role" or "instanceProfile" for Karpenter to launch nodes
  
  role: "${karpenter_node_instance_role}"

  amiSelectorTerms:
    # Select EKS optimized AL2023 AMIs with version `v20240703`. This term is mutually
    # exclusive and can't be specified with other terms.
    - alias: ${karpenter_node_ami}      # al2023@v20240703

  # Optional, propagates tags to underlying EC2 resources
  tags:
    Name: ${cluster_name}-${nodeclass_name}
    karpenter.sh/discovery: ${cluster_name}
    IntentLabel: "apps"

  # Optional, configures IMDS for the instance
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 1 # This is changed to disable IMDS access from containers not on the host network
    httpTokens: required

  # Optional, configures storage devices for the instance
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: "${karpenter_node_root_vol_size}"
        volumeType: gp3

  # Optional, overrides autogenerated userdata with a merge semantic
  userData: |
    ${karpenter_userdata} 

  # Optional, configures detailed monitoring for the instance
  detailedMonitoring: false

  # Optional, configures if the instance should be launched with an associated public IP address.
  # If not specified, the default value depends on the subnet's public IP auto-assign setting.
  associatePublicIPAddress: false